name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write
  actions: write

# Allow only one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Enable GitHub Pages if not already enabled
      - name: Enable GitHub Pages
        run: |
          # Get repository name from GitHub context
          REPO_NAME="${GITHUB_REPOSITORY#*/}"
          OWNER="${GITHUB_REPOSITORY%/*}"

          echo "Enabling GitHub Pages for $OWNER/$REPO_NAME"

          # Try to create GitHub Pages site settings
          # Note: This might fail if already configured, which is fine
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$OWNER/$REPO_NAME/pages" \
            -d '{"source":{"branch":"gh-pages","path":"/"}}' || true

          # Update GitHub Pages settings to use GitHub Actions
          curl -X PUT \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$OWNER/$REPO_NAME/pages" \
            -d '{"build_type":"workflow"}' || true
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          enablement: true
      - name: Install dependencies
        run: npm ci
      - name: Build with Next.js
        run: npm run build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      # Create gh-pages branch if it doesn't exist
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create gh-pages branch if needed
        run: |
          # Configure Git identity
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if ! git ls-remote --heads origin gh-pages | grep gh-pages; then
            echo "Creating gh-pages branch"
            git checkout --orphan gh-pages
            git reset --hard
            git commit --allow-empty -m "Initial gh-pages commit"
            git push origin gh-pages
            git checkout -
          else
            echo "gh-pages branch already exists"
          fi

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
